name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: 'Build Inventory Image'
      run: |
        docker build . --tag ghcr.io/dknoern/books:latest
        docker push ghcr.io/dknoern/books:latest

  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy Helm
      uses: bitovi/github-actions-deploy-eks-helm@v1.2.8
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
        cluster-name: dktest
        config-files: .github/values/dev.yaml
        chart-path: chart/
        namespace: default
        values: key1=value1,key2=value2
        name: release0